name: Jekyll
on:
  pull_request:
    branches:
      - master

jobs:
  jekyll:
    name: Linux
    runs-on: ubuntu-latest
    env:
      working-directory: './docs'
    steps:
      - uses: actions/checkout@v2
      - uses: jerryjvl/jekyll-build-action@v1
        name: 'Build'
        working-directory: ${{ env.working-directory }}
